####################################################################
#                        Database Settings                         #
####################################################################

user: postgres
dbname: bot
password: 2342789tf2S
host: 0.0.0.0
port: 5432
