####################################################################
#                        Database Settings                         #
####################################################################

user: postgres
dbname: dis_test
password: Hash#2Cipher
host: localhost
port: 5432
