####################################################################
#                        Database Settings                         #
####################################################################

user: user
dbname: bot
password: pass
host: localhost
port: 40041

