####################################################################
#                        Database Settings                         #
####################################################################

user: user
dbname: bot
password: pass
host: 0.0.0.0
port: 5432
