####################################################################
#                        Database Settings                         #
####################################################################

user: docker
dbname: docker
password: docker
host: 0.0.0.0
port: 5432