####################################################################
#                        Database Settings                         #
####################################################################

user: 
dbname: chenzhitao
password: 
host: localhost
port: 8000